### ISSUE TITLE
How to use fnn for downstream tasks? What's the version of all packages?

### ISSUE THREAD

**Issue by BEbillionaireUSD** [williamgilpin/fnn#7]
Hi, your work is really impressive. But I don't have many physics backgrounds so that I cannot fully understand your paper. 
I want to do a multivariate time series classification task, and I try the demos you provide. 

- The dataset "pendulum_train.csv" have a (5927, 4) matrix and the demo code only adopts 2 dimensions so that the input is a (5927, 2) matrix. It is embedded into a (5917, 10) matrix. But why 5917? How it comes out? If I want to calculate the distance between the embeddings of two samples, should I flatten the embedded matrix (i.e. from a (5917, 10) matrix to a 59170 vector)?

- Besides, could you please tell me the specific versions of all used packages? I have some trouble after upgrading NumPy.

**Comment by williamgilpin** [comment]
Hi @cherylLbt ! The embedding loses 10 timepoints because the autoencoder's first step is to create a lagged embedding, and the number of lags defaults to 10. 

Would you mind posting your package version? I am worried that there is an issue with newer editions of TensorFlow. Right now I am using TensorFlow 2.5 and numpy 1.19.5, but I haven't upgraded in a while.

**Comment by BEbillionaireUSD** [comment]
Thanks for your reply! My tensorflow is 2.2 and my numpy is 1.21. I will change them in order to make it consistent with the version you are using.
